HTTP/1.1 200 OK
cf-cache-status: DYNAMIC
cf-ray: 8cb45e0cc8ce6b50-DFW
connection: keep-alive
content-encoding: br
content-type: application/json
date: Mon, 30 Sep 2024 12:55:27 GMT
nel: {"report_to":"heroku-nel","max_age":3600,"success_fraction":0.005,"failure_fraction":0.05,"response_headers":["Via"]}
report-to: {"group":"heroku-nel","max_age":3600,"endpoints":[{"url":"https://nel.heroku.com/reports?ts=1727700927&sid=812dcc77-0bd0-43b1-a5f1-b25750382959&s=2GgkGKZ5CKA%2F8RjV9HxuRWxaEjM6mSem7QFS04FUSdU%3D"}]}
reporting-endpoints: heroku-nel=https://nel.heroku.com/reports?ts=1727700927&sid=812dcc77-0bd0-43b1-a5f1-b25750382959&s=2GgkGKZ5CKA%2F8RjV9HxuRWxaEjM6mSem7QFS04FUSdU%3D
server: cloudflare
transfer-encoding: chunked
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
via: 1.1 vegur

{
  "categories": [],
  "created_at": "2020-01-05 13:42:22.980058",
  "icon_url": "https://api.chucknorris.io/img/avatar/chuck-norris.png",
  "id": "Je9eNMeHRHyKAfAam0v0mQ",
  "updated_at": "2020-01-05 13:42:22.980058",
  "url": "https://api.chucknorris.io/jokes/Je9eNMeHRHyKAfAam0v0mQ",
  "value": "After The Hulk lost an arm wrestling contest with Chuck Norris, he turned green with envy."
}